BankApp.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BankApp.Domain;
using BankApp.App.ViewModels;
using BankApp.App;
using BankApp.App.Accounts.Queries;
using Microsoft.AspNetCore.Authorization;

namespace BankApp.Web.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        // GET: /<controller>/
        public IActionResult Index()
        {
            IndexViewModel model = new IndexViewModel();

            return View(model);
        }
    }
}

BankApp.Web/ViewComponents/HeaderViewComponent.cs
using BankApp.App.Accounts.Queries;
using BankApp.App.ViewModels;
using BankApp.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankApp.Web.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public HeaderViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {   
            return View();
        }
    }
}

BankApp.Web/Views/Home/Index.cshtml
@model BankApp.App.ViewModels.IndexViewModel


@{
    ViewData["Title"] = "Home - BankApp";
}
    <div>
        @await Component.InvokeAsync("Header")
    </div>

<div class="row  text-center features-icons">
    <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
                <i class="icon-screen-desktop m-auto text-primary"></i>
            </div>
            <h3>@Model.TotalAccounts accounts</h3>
            <p class="lead mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed viverra egestas feugiat. Nunc porta dictum pellentesque.</p>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
                <i class="icon-layers m-auto text-primary"></i>
            </div>
            <h3>@Model.TotalCustomers customers</h3>
            <p class="lead mb-0">Cras eu nisl ipsum. Sed ornare eu est vitae dictum. Nullam interdum nunc non est egestas sodales. </p>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
                <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3>Total balance: @Model.TotalBalance kr</h3>
            <p class="lead mb-0">Vivamus quam massa, tincidunt congue placerat ac, aliquam eu nisl. </p>
        </div>
    </div>
</div>